export type ProjectCategory =
  | "Residential"
  | "Commercial"
  | "Institutional"
  | "Urban"
  | "Hospitality";

export type Project = {
  id: string;
  slug: string;
  title: string;
  category: ProjectCategory;
  location: string;
  year: string;
  cover: string;
  images: string[];
  summary: string;
  // Architectural Metadata
  bedrooms?: number;
  bathrooms?: number;
  area?: string; 
  mapUrl?: string; 
};

export const PROJECTS: Project[] = [
  {
    id: "p01",
    slug: "project-01",
    title: "Residential Concept",
    category: "Residential",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p01-1.png",
    images: ["/p01-2.png", "/p01-3.png", "/p01-4.png"], 
    summary: "A residential design study focused on spatial clarity, proportion, privacy, and long-term architectural value.",
    bedrooms: 5,
    bathrooms: 6,
    area: "620 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p02",
    slug: "project-02",
    title: "Private Residence",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/p02-1.png",
    images: ["/project-14.png", "/project-21.png", "/project-22.png"],
    summary: "A private residential project shaped through context, material logic, and refined living experience.",
    bedrooms: 4,
    bathrooms: 4,
    area: "450 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p03",
    slug: "project-03",
    title: "Urban Villa",
    category: "Residential",
    location: "East Africa",
    year: "2024",
    cover: "/p03-1.png",
    images: ["/project-21.png", "/project-22.png", "/project-10.png"],
    summary: "A contemporary villa study balancing architectural identity, landscape, and practical buildability.",
    bedrooms: 6,
    bathrooms: 7,
    area: "850 sqm",
    mapUrl: "https://maps.google.com/maps?q=East+Africa&z=6&output=embed"
  },
  {
    id: "p04",
    slug: "project-04",
    title: "Commercial Development",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p04-1.png",
    images: ["/project-22.png", "/project-10.png", "/project-36.png"],
    summary: "A commercial project environment focused on visibility, circulation, usability, and development value.",
    area: "2,400 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p05",
    slug: "project-05",
    title: "Hospitality Concept",
    category: "Hospitality",
    location: "Regional",
    year: "2024",
    cover: "/p05-1.png",
    images: ["/project-10.png", "/project-36.png", "/project-23.png"],
    summary: "A hospitality-oriented study shaped around atmosphere, comfort, guest experience, and spatial flow.",
    bedrooms: 45,
    bathrooms: 45,
    area: "3,200 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=10&output=embed"
  },
  {
    id: "p06",
    slug: "project-06",
    title: "Mixed-use Study",
    category: "Urban",
    location: "Africa",
    year: "2024",
    cover: "/p06-1.png",
    images: ["/project-36.png", "/project-23.png", "/project-9.png"],
    summary: "A mixed-use development study combining commercial logic, urban presence, and planning awareness.",
    area: "1.2 Hectares",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=12&output=embed"
  },
  {
    id: "p07",
    slug: "project-07",
    title: "Hill View House",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/p07-1.png",
    images: ["/project-23.png", "/project-9.png", "/project-8.png"],
    summary: "A residential project responding to topography, views, climate, and long-term living comfort.",
    bedrooms: 3,
    bathrooms: 3,
    area: "320 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p08",
    slug: "project-08",
    title: "Private Estate",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/p08-1.png",
    images: ["/project-9.png", "/project-8.png", "/project-45.png"],
    summary: "A private estate concept developed through landscape integration, privacy, and architectural restraint.",
    bedrooms: 7,
    bathrooms: 8,
    area: "1,100 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p09",
    slug: "project-09",
    title: "Urban Residence",
    category: "Urban",
    location: "East Africa",
    year: "2024",
    cover: "/p09-1.png",
    images: ["/project-8.png", "/project-45.png", "/project-46.png"],
    summary: "An urban residential study focused on density, privacy, frontage, and contextual development.",
    bedrooms: 4,
    bathrooms: 4,
    area: "800 sqm",
    mapUrl: "https://maps.google.com/maps?q=East+Africa&z=6&output=embed"
  },
  {
    id: "p10",
    slug: "project-10",
    title: "Institutional Study",
    category: "Institutional",
    location: "Rwanda",
    year: "2024",
    cover: "/p10-1.png",
    images: ["/project-45.png", "/project-46.png", "/project-30.png"],
    summary: "An institutional planning study shaped by circulation, durability, public use, and clear organization.",
    area: "4,500 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p11",
    slug: "project-11",
    title: "Planning Study",
    category: "Urban",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p11-1.png",
    images: ["/project-46.png", "/project-30.png", "/project-28.png"],
    summary: "A planning-oriented development study focused on site logic, access, density, and future value.",
    area: "3.5 Hectares",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p12",
    slug: "project-12",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p12-1.png",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "1,800 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p13",
    slug: "project-13",
    title: "Residential Concept",
    category: "Residential",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p13-1.png",
    images: ["/p01-2.png", "/p01-3.png", "/p01-4.png"], 
    summary: "A residential design study focused on spatial clarity, proportion, privacy, and long-term architectural value.",
    bedrooms: 5,
    bathrooms: 5,
    area: "580 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p14",
    slug: "project-14",
    title: "Private Residence",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/p14-1.png",
    images: ["/project-14.png", "/project-21.png", "/project-22.png"],
    summary: "A private residential project shaped through context, material logic, and refined living experience.",
    bedrooms: 4,
    bathrooms: 5,
    area: "420 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p15",
    slug: "project-15",
    title: "Urban Villa",
    category: "Residential",
    location: "East Africa",
    year: "2024",
    cover: "/p15-1.png",
    images: ["/project-21.png", "/project-22.png", "/project-10.png"],
    summary: "A contemporary villa study balancing architectural identity, landscape, and practical buildability.",
    bedrooms: 5,
    bathrooms: 6,
    area: "600 sqm",
    mapUrl: "https://maps.google.com/maps?q=East+Africa&z=6&output=embed"
  },
  {
    id: "p16",
    slug: "project-16",
    title: "Commercial Development",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p16-1.png",
    images: ["/project-22.png", "/project-10.png", "/project-36.png"],
    summary: "A commercial project environment focused on visibility, circulation, usability, and development value.",
    area: "3,100 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p17",
    slug: "project-17",
    title: "Hospitality Concept",
    category: "Hospitality",
    location: "Regional",
    year: "2024",
    cover: "/project-100.png",
    images: ["/project-10.png", "/project-36.png", "/project-23.png"],
    summary: "A hospitality-oriented study shaped around atmosphere, comfort, guest experience, and spatial flow.",
    bedrooms: 60,
    bathrooms: 65,
    area: "4,800 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=10&output=embed"
  },
  {
    id: "p18",
    slug: "project-18",
    title: "Mixed-use Study",
    category: "Urban",
    location: "Africa",
    year: "2024",
    cover: "/project-08.png",
    images: ["/project-36.png", "/project-23.png", "/project-9.png"],
    summary: "A mixed-use development study combining commercial logic, urban presence, and planning awareness.",
    area: "2.4 Hectares",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=10&output=embed"
  },
  {
    id: "p19",
    slug: "project-19",
    title: "Hill View House",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/project-09.png",
    images: ["/project-23.png", "/project-9.png", "/project-8.png"],
    summary: "A residential project responding to topography, views, climate, and long-term living comfort.",
    bedrooms: 4,
    bathrooms: 4,
    area: "380 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p20",
    slug: "project-20",
    title: "Private Estate",
    category: "Residential",
    location: "Rwanda",
    year: "2024",
    cover: "/p20-1.png",
    images: ["/project-9.png", "/project-8.png", "/project-45.png"],
    summary: "A private estate concept developed through landscape integration, privacy, and architectural restraint.",
    bedrooms: 8,
    bathrooms: 9,
    area: "1,500 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p21",
    slug: "project-21",
    title: "Urban Residence",
    category: "Urban",
    location: "East Africa",
    year: "2024",
    cover: "/p21-1.jpg",
    images: ["/project-8.png", "/project-45.png", "/project-46.png"],
    summary: "An urban residential study focused on density, privacy, frontage, and contextual development.",
    bedrooms: 3,
    bathrooms: 4,
    area: "950 sqm",
    mapUrl: "https://maps.google.com/maps?q=East+Africa&z=6&output=embed"
  },
  {
    id: "p22",
    slug: "project-22",
    title: "Institutional Study",
    category: "Institutional",
    location: "Rwanda",
    year: "2024",
    cover: "/p22-1.jpg",
    images: ["/project-45.png", "/project-46.png", "/project-30.png"],
    summary: "An institutional planning study shaped by circulation, durability, public use, and clear organization.",
    area: "5,200 sqm",
    mapUrl: "https://maps.google.com/maps?q=Rwanda&z=12&output=embed"
  },
  {
    id: "p23",
    slug: "project-23",
    title: "Planning Study",
    category: "Urban",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p23-1.jpg",
    images: ["/project-46.png", "/project-30.png", "/project-28.png"],
    summary: "A planning-oriented development study focused on site logic, access, density, and future value.",
    area: "1.8 Hectares",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p24",
    slug: "project-24",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p24-1.jpg",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p25",
    slug: "project-25",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p25-1.jpg",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p26",
    slug: "project-26",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p26-1.png",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p27",
    slug: "project-27",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p27-1.png",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p28",
    slug: "project-28",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p28-1.jpg",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p29",
    slug: "project-29",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/project-44.jpg",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p30",
    slug: "project-30",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/project-030.jpg",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
  {
    id: "p31",
    slug: "project-31",
    title: "Commercial Block",
    category: "Commercial",
    location: "Kigali, Rwanda",
    year: "2024",
    cover: "/p31-1.png",
    images: ["/project-30.png", "/project-28.png", "/project-14.png"],
    summary: "A commercial block concept exploring frontage, public interface, tenant flexibility, and buildability.",
    area: "2,000 sqm",
    mapUrl: "https://maps.google.com/maps?q=Kigali,Rwanda&z=14&output=embed"
  },
];