import { defineArrayMember, defineField, defineType } from "sanity";

const imageWithAlt = (name: string, title: string, group?: string) =>
  defineField({
    name,
    title,
    type: "image",
    options: { hotspot: true },
    group,
    fields: [defineField({ name: "alt", title: "Alternative text", type: "string" })],
  });

const textPair = (titleLabel = "Title", textLabel = "Description") =>
  defineArrayMember({
    type: "object",
    fields: [
      defineField({ name: "title", title: titleLabel, type: "string" }),
      defineField({ name: "text", title: textLabel, type: "text", rows: 3 }),
    ],
    preview: { select: { title: "title", subtitle: "text" } },
  });

export const domicilePageType = defineType({
  name: "domicilePage",
  title: "DŌMICILE Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "explained", title: "How it works" },
    { name: "care", title: "Care in practice" },
    { name: "owner", title: "Owner view" },
    { name: "properties", title: "Properties" },
    { name: "trust", title: "Trust & FAQ" },
    { name: "enquiry", title: "Enquiry" },
    { name: "seo", title: "SEO & sharing" },
  ],
  fields: [
    defineField({ name: "heroEyebrow", title: "Hero label", type: "string", group: "hero" }),
    defineField({ name: "heroHeading", title: "Hero heading", type: "text", rows: 2, group: "hero" }),
    defineField({ name: "heroLead", title: "Hero introduction", type: "text", rows: 4, group: "hero" }),
    defineField({ name: "primaryCtaLabel", title: "Primary CTA label", type: "string", group: "hero" }),
    defineField({ name: "secondaryCtaLabel", title: "Secondary CTA label", type: "string", group: "hero" }),
    imageWithAlt("heroImage", "Hero image", "hero"),
    defineField({
      name: "heroFacts",
      title: "Hero facts",
      type: "array",
      group: "hero",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.max(3),
    }),

    defineField({ name: "explainedTag", title: "Section label", type: "string", group: "explained" }),
    defineField({ name: "explainedHeading", title: "Heading", type: "string", group: "explained" }),
    defineField({ name: "explainedLead", title: "Introduction", type: "text", rows: 5, group: "explained" }),
    defineField({ name: "explainedQuote", title: "Photo quote", type: "text", rows: 3, group: "explained" }),
    defineField({ name: "explainedPhotoLabel", title: "Photo label", type: "string", group: "explained" }),
    defineField({ name: "explainedPhotoStatus", title: "Photo status", type: "string", group: "explained" }),
    imageWithAlt("explainedImage", "How-it-works image", "explained"),
    defineField({
      name: "explanationSteps",
      title: "How it works steps",
      type: "array",
      group: "explained",
      of: [textPair("Step title", "Step description")],
      validation: (rule) => rule.max(4),
    }),

    defineField({ name: "careTag", title: "Section label", type: "string", group: "care" }),
    defineField({ name: "careHeading", title: "Heading", type: "string", group: "care" }),
    defineField({ name: "careIntro", title: "Introduction", type: "text", rows: 4, group: "care" }),
    imageWithAlt("carePrimaryImage", "Primary care image", "care"),
    imageWithAlt("careSecondaryImage", "Secondary care image", "care"),
    defineField({
      name: "careItems",
      title: "Care cards",
      type: "array",
      group: "care",
      of: [defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "label", title: "Label", type: "string" }),
          defineField({ name: "text", title: "Description", type: "text", rows: 3 }),
        ],
        preview: { select: { title: "label", subtitle: "text" } },
      })],
      validation: (rule) => rule.max(4),
    }),

    defineField({ name: "ownerTag", title: "Section label", type: "string", group: "owner" }),
    defineField({ name: "ownerHeading", title: "Heading", type: "string", group: "owner" }),
    defineField({ name: "ownerIntro", title: "Introduction", type: "text", rows: 3, group: "owner" }),
    imageWithAlt("ownerImage", "Owner-view background image", "owner"),

    defineField({ name: "propertiesTag", title: "Section label", type: "string", group: "properties" }),
    defineField({ name: "propertiesHeading", title: "Heading", type: "text", rows: 2, group: "properties" }),
    defineField({ name: "propertiesIntro", title: "Introduction", type: "text", rows: 3, group: "properties" }),
    defineField({
      name: "properties",
      title: "Property stories",
      type: "array",
      group: "properties",
      of: [defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "status", title: "Status label", type: "string" }),
          defineField({ name: "title", title: "Property title", type: "string" }),
          defineField({ name: "copy", title: "Description", type: "text", rows: 3 }),
          defineField({
            name: "image",
            title: "Property image",
            type: "image",
            options: { hotspot: true },
            fields: [defineField({ name: "alt", title: "Alternative text", type: "string" })],
          }),
        ],
        preview: { select: { title: "title", subtitle: "status", media: "image" } },
      })],
      validation: (rule) => rule.max(3),
    }),

    defineField({ name: "trustTag", title: "Trust label", type: "string", group: "trust" }),
    defineField({ name: "trustHeading", title: "Trust heading", type: "string", group: "trust" }),
    defineField({ name: "trustText", title: "Trust text", type: "text", rows: 4, group: "trust" }),
    defineField({ name: "faqTag", title: "FAQ label", type: "string", group: "trust" }),
    defineField({
      name: "faqs",
      title: "Frequently asked questions",
      type: "array",
      group: "trust",
      of: [defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "question", title: "Question", type: "string" }),
          defineField({ name: "answer", title: "Answer", type: "text", rows: 4 }),
        ],
        preview: { select: { title: "question", subtitle: "answer" } },
      })],
      validation: (rule) => rule.max(6),
    }),

    defineField({ name: "enquiryTag", title: "Section label", type: "string", group: "enquiry" }),
    defineField({ name: "enquiryHeading", title: "Heading", type: "string", group: "enquiry" }),
    defineField({ name: "enquiryIntro", title: "Introduction", type: "text", rows: 4, group: "enquiry" }),
    imageWithAlt("enquiryImage", "Enquiry image", "enquiry"),
    defineField({ name: "email", title: "DŌMICILE email", type: "email", group: "enquiry" }),
    defineField({ name: "phoneLabel", title: "Displayed phone / WhatsApp", type: "string", group: "enquiry" }),
    defineField({ name: "whatsappUrl", title: "WhatsApp URL", type: "url", group: "enquiry" }),
    defineField({ name: "locationLabel", title: "Location label", type: "string", group: "enquiry" }),
    defineField({ name: "formKicker", title: "Form label", type: "string", group: "enquiry" }),
    defineField({ name: "formHeading", title: "Form heading", type: "string", group: "enquiry" }),
    defineField({ name: "formIntro", title: "Form introduction", type: "text", rows: 3, group: "enquiry" }),
    defineField({ name: "submitLabel", title: "Submit button label", type: "string", group: "enquiry" }),
    defineField({ name: "successKicker", title: "Success label", type: "string", group: "enquiry" }),
    defineField({ name: "successHeading", title: "Success heading", type: "string", group: "enquiry" }),
    defineField({ name: "successText", title: "Success text", type: "text", rows: 3, group: "enquiry" }),
    defineField({ name: "footerDescriptor", title: "Footer descriptor", type: "string", group: "enquiry" }),

    defineField({ name: "seoTitle", title: "Google title", type: "string", group: "seo", validation: (rule) => rule.max(65) }),
    defineField({ name: "seoDescription", title: "Google description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(170) }),
    imageWithAlt("shareImage", "Social sharing image", "seo"),
  ],
  initialValue: {
    heroEyebrow: "PROPERTY MANAGEMENT · KIGALI",
    heroHeading: "Your property,\nhandled.",
    heroLead: "One dependable local point of contact for property oversight, maintenance, owner-away care and follow-through.",
    primaryCtaLabel: "START AN ENQUIRY",
    secondaryCtaLabel: "UNDERSTAND DŌMICILE",
    heroFacts: ["KIGALI BASED", "ONE RESPONSIBLE CONTACT", "PRIVATE BY DEFAULT"],
    explainedTag: "01 / DŌMICILE EXPLAINED",
    explainedHeading: "What DŌMICILE actually does.",
    explainedLead: "DŌMICILE is the local operating layer between you and everything that needs attention at your property. Instead of coordinating inspectors, technicians, repairs, access and updates separately, you have one responsible point of contact.",
    explainedQuote: "You should not need six conversations to know what happened at your own property.",
    explainedPhotoLabel: "PRIVATE RESIDENCE",
    explainedPhotoStatus: "Routine care active",
    explanationSteps: [
      { _key: "step-1", title: "We understand the property", text: "We establish the home, access arrangements, priorities, contacts and the level of authority you want DŌMICILE to hold." },
      { _key: "step-2", title: "We become the local point of contact", text: "Routine checks, technicians, repairs and property matters move through one responsible desk instead of several disconnected conversations." },
      { _key: "step-3", title: "You approve what matters", text: "Costs, works and decisions that require your authority stay visible and are confirmed before action, except where agreed emergency authority applies." },
      { _key: "step-4", title: "You keep the record", text: "Photos, notes, reports, approvals and completed matters stay connected to the same property so you can see what happened and what comes next." },
    ],
    careTag: "02 / CARE IN PRACTICE",
    careHeading: "The property stays visible. The coordination stays quiet.",
    careIntro: "Photography is part of the record—not decoration. The home, the issue, the work and the follow-up remain easy to understand.",
    careItems: [
      { _key: "care-1", label: "PROPERTY OVERSIGHT", text: "Scheduled checks and a dependable local presence." },
      { _key: "care-2", label: "MAINTENANCE & REPAIRS", text: "Issues scoped, coordinated and followed through." },
      { _key: "care-3", label: "OWNER-AWAY CARE", text: "Local presence when you are not in Kigali—with the record kept clear for you." },
      { _key: "care-4", label: "PROPERTY WORKS", text: "Repairs and improvements coordinated with clear owner approval before action." },
    ],
    ownerTag: "03 / OWNER VIEW",
    ownerHeading: "Visibility without chasing updates.",
    ownerIntro: "See what happened, what needs approval and what comes next.",
    propertiesTag: "04 / SELECTED PROPERTIES",
    propertiesHeading: "Real homes.\nQuietly looked after.",
    propertiesIntro: "These visual examples show the kind of residential environments DŌMICILE is designed to care for.",
    properties: [
      { _key: "property-1", status: "ROUTINE CARE ACTIVE", title: "Private residence", copy: "Scheduled checks, issue follow-through and one clear local contact for the owner." },
      { _key: "property-2", status: "INSPECTION SCHEDULED", title: "Residential estate", copy: "Property readiness, maintenance coordination and owner visibility kept in one place." },
      { _key: "property-3", status: "OWNER-AWAY CARE", title: "Private home", copy: "Local presence while the owner is away, with private reporting and direct escalation when needed." },
    ],
    trustTag: "BACKED BY IMVO GROUP",
    trustHeading: "Property care with built-environment thinking behind it.",
    trustText: "DŌMICILE combines day-to-day property coordination with IMVO Group’s design, technical and built-environment perspective.",
    faqTag: "FREQUENTLY ASKED QUESTIONS",
    faqs: [
      { _key: "faq-1", question: "Do I need to live outside Rwanda?", answer: "No. DŌMICILE is for owners abroad, frequent travellers and Kigali-based owners who want reliable delegated property care." },
      { _key: "faq-2", question: "Can you manage one property only?", answer: "Yes. The service can be shaped around one home, several properties or a defined one-off need." },
      { _key: "faq-3", question: "How are repairs approved?", answer: "The approval process is agreed during onboarding. Work requiring owner approval does not proceed until authority is confirmed." },
      { _key: "faq-4", question: "What happens if something is urgent?", answer: "The matter is triaged, the owner is contacted and DŌMICILE acts within any pre-agreed emergency authority where applicable." },
      { _key: "faq-5", question: "Will my property appear on the website?", answer: "No, not by default. Client properties and identifying information are public only when the owner has explicitly agreed." },
      { _key: "faq-6", question: "Which areas do you serve?", answer: "DŌMICILE is currently focused on properties across Kigali, Rwanda." },
    ],
    enquiryTag: "START WITH A CONVERSATION",
    enquiryHeading: "Tell us about your property.",
    enquiryIntro: "This is an enquiry, not a registration. We’ll contact you to understand the property and what you need.",
    email: "domicile@imvogroup.com",
    phoneLabel: "+250 799 409 409",
    whatsappUrl: "https://wa.me/250799409409",
    locationLabel: "KIGALI · RWANDA",
    formKicker: "PROPERTY ENQUIRY",
    formHeading: "What should we know?",
    formIntro: "A first conversation is enough to start. Phone or email is enough.",
    submitLabel: "SEND TO DŌMICILE",
    successKicker: "ENQUIRY RECEIVED",
    successHeading: "Thank you.",
    successText: "We’ll review the details and contact you directly.",
    footerDescriptor: "PROPERTY MANAGEMENT BY IMVO GROUP",
    seoTitle: "DŌMICILE | Property Management",
    seoDescription: "DŌMICILE is property management by IMVO Group for owners who want one reliable point of contact for the ongoing care, maintenance and coordination of their property in Kigali, Rwanda.",
  },
  preview: { prepare: () => ({ title: "DŌMICILE", subtitle: "Property management page content" }) },
});
